### Computing Q Vaues using Bellman's updated equation ###

Bellmann Equation is: $Q(s,a) = Q(s,a) + \alpha (R_s + \gamma * max(Q(s',a') - Q(s,a))$

where $Q(s,a)$ is the $Q$ value of the state it is in.

#### The method for training an agent using Q-Learning is done as follows: ####
    - In the start state the agent can take any random action to get to the next state
    - From this state the Agent takes the optimal path as per the Bellman equation till end of episode.
    - When the episode is over a new episode starts but the Q-Values are carried over to the next episode
    - Many episodes are iteratively run till the Q-Values of any of the state, action pairs do not change (Optimal policy)
    - The Q-Values are populated in a Q-Table with columns as actions and rows as states.

For the MineExplorer Exercise and to make this process intuitively clear, I have shown the sample calculation for 2 episodes.


1. Keep in mind the MineExplorer has 6 states with 2 of them being terminal states.
2. The terminal state 1 gives a reward of 100 and the terminal state 6 gives a reward of 40.
3. All other states give a reward of 0.
4. Mine explorer has two actions - move left (0) or move right (1).
5. I will take the gamma as in the class example (0.5) and will assume alpha = 1 (you will use values given in the exercise).
6. Let the start state always be 3.

In [59]:
import numpy as np

In [ ]:
# Create a Q-Table
Q = np.zeros((6,2)) # 1st column represents action 'left' and 2nd column represents action 'right'

alpha = 1.  # Learningrate
gamma = 0.5 # Discount factor

# Populate the terminal states with rewards
Q[0][0] = 100
Q[5][1] = 40

reward = [100,0,0,0,0,40] # The reward system
action = [0,1]            # The action codes for 'left','right'

print(f"Q-Table at start\n{Q}")


# Episode 1: 
# Remember python counts from 0
# Starts at state 2 and let the agent make a random first action to the left
# It then moves to the next state, which is 1.

episode = True # Indication that episode is not done

state = 2 # Set start state 

actions = action[0] # First random action 

# Compute Q value of each state till the episode ends
while episode:
    if actions == 0:  # Goes left
        Q[state,action[0]] = Q[state,action[0]] + alpha * (reward[state] + gamma * np.max(Q[state-1]) - Q[state,action[0]] )
    else:           # Goes right
        Q[state,action[0]] = Q[state,action[0]] + alpha * (reward[state] + gamma * np.max(Q[state+1]) - Q[state,action[0]] )

    # the next state is 1
    if actions == 0:
        state = state - 1
    else:
        state = state + 1   
    
    if state == 0 or state == 5:
        episode = False
        
print(f"Q Values after Episode 1:\n{Q}")

# Let us do a 2nd episode with statrt state = 2 (already set)
# Let the agent take a random first action as right this time and then follow the optimal route
# Compute Q value of each state till the episode ends
# Note that the Q-Table remains as last updated in Episode 1

episode = True # Indication that episode is not done

state = 2 # Reset start state 

actions = action[1] # Random right step first

while episode:
    if actions == 0:  # Goes left
        Q[state,action[0]] = Q[state,action[0]] + alpha * (reward[state] + gamma * np.max(Q[state-1]) - Q[state,action[0]] )
    else:           # Goes right
        Q[state,action[0]] = Q[state,action[0]] + alpha * (reward[state] + gamma * np.max(Q[state+1]) - Q[state,action[0]] )

    # the next state is 1
    if actions ==0:
        state = state - 1
    else:
        state = state + 1
    
        
    actions = action[0] # Then continue left as it is the optimal action   
    
    if state == 0 or state == 5:
        episode = False
        
print(f"\nQ Values after Episode 2:\n{Q}")   


Q-Table at start
[[100.   0.]
 [  0.   0.]
 [  0.   0.]
 [  0.   0.]
 [  0.   0.]
 [  0.  40.]]
0
Q Values after Episode 1:
[[100.   0.]
 [ 50.   0.]
 [  0.   0.]
 [  0.   0.]
 [  0.   0.]
 [  0.  40.]]

Q Values after Episode 2:
[[100.   0.]
 [ 50.   0.]
 [ 25.   0.]
 [  0.   0.]
 [  0.   0.]
 [  0.  40.]]


### Please Note: ###

1. This is just bare code to show how the equations are implemented and computation is done
2. I have assumed what the random action will be wheras when you code the whole exercise you will have to generate that random action
3. Make your code a combination of for loops for number of episodes and while loop for each episode - that is the most efficient way.
4. Study and understand how I have implemented and computed the Bellman's equation.
